version: '2.1'
services:
  nginx:
    image: nginx:1.15-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/nginx:/etc/nginx/conf.d
      - /opt/ssl/conf:/etc/letsencrypt
      - /opt/ssl/www:/var/www/certbot
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /opt/ssl/conf:/etc/letsencrypt
      - /opt/ssl/www:/var/www/certbot
