version: '2.1'
services:
  nginx:
    image: nginx:1.15-alpine
    container_name: nginx
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/nginx:/etc/nginx/conf.d
      - /opt/ssl/conf:/etc/letsencrypt
      - /opt/ssl/www:/var/www/certbot
  certbot:
    image: certbot/certbot
    container_name: certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - /opt/ssl/conf:/etc/letsencrypt
      - /opt/ssl/www:/var/www/certbot
